### ISSUE TITLE
Incorrect definition for change()

### ISSUE THREAD

**Issue by eklavyadev** [PratyushTheCoder/computerspeak-4.2.50#1]
Defined as - 0 for male and 1 for female

It is not predefined as such you mentioned in README.md, it is based on indexes the TTS Voice is placed in local machine and for the one who had installed other voices can also use change(3 or 4) as function.

**Comment by PratyushTheCoder** [comment]
Hi Eklavya, thanks for the clarification, and can you tell me how can I fix
it

**Comment by PratyushTheCoder** [comment]
As i am not able to understand the issue

**Comment by PratyushTheCoder** [comment]
Ok thanks I will correct it, 😅
